# Generated by Django 2.0 on 2017-12-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20, verbose_name='Name')),
                ('caddr', models.CharField(max_length=50, null=True, verbose_name='Address')),
                ('cphone', models.CharField(max_length=15, null=True, verbose_name='Phone')),
                ('cwechat', models.CharField(max_length=20, null=True, verbose_name='Wechat')),
                ('cdate', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(verbose_name='Date Ordered')),
                ('oshipdate', models.DateTimeField(null=True, verbose_name='Date Shipped')),
                ('opaid', models.BooleanField(verbose_name='Is this order paid?')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total amount')),
                ('opaymentmethod', models.CharField(max_length=20, null=True, verbose_name='Payment method')),
                ('ostatus', models.CharField(max_length=20, verbose_name='Status')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
            ],
        ),
    ]
