# Generated by Django 2.0 on 2017-12-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=40, verbose_name='Product Name')),
                ('ptype', models.CharField(max_length=20, null=True, verbose_name='Product Type')),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Product Cost')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Product Price')),
            ],
        ),
    ]
