# Generated by Django 2.0 on 2017-12-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pstatus',
            field=models.CharField(max_length=15, null=True, verbose_name='Status'),
        ),
    ]
