# Generated by Django 2.0 on 2018-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_pstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pweight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Weight'),
        ),
    ]
