# Generated by Django 2.0 on 2017-12-28 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquantity', models.IntegerField(verbose_name='Order Quantity')),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Price')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Order')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ordercontains',
            unique_together={('oid', 'pid')},
        ),
    ]
