# Generated by Django 2.0 on 2018-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_pweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cdate',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
    ]
