# Generated by Django 2.0 on 2017-12-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171228_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventorycontains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iquantity', models.IntegerField(verbose_name='Inventory Quantity')),
                ('iprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Inventory Price')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Inventory')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventorycontains',
            unique_together={('iid', 'pid')},
        ),
    ]
