# Generated by Django 2.0 on 2017-12-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171228_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oshipping',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Shipping Cost'),
        ),
    ]
