# Generated by Django 2.0 on 2017-12-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_order_oshipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='caddr',
            field=models.CharField(max_length=80, null=True, verbose_name='Address'),
        ),
    ]
