# Generated by Django 2.0 on 2017-12-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171228_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='caddr',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
    ]
